platform :ios, '12.0'
use_frameworks!

target 'iosApp' do
  # 本地组件
  pod 'KuiklyNotificationIOS', :path => '../'
  # KMP 跨端层（由 Gradle cocoapods 集成生成，通常在 Xcode 侧通过 Gradle 同步）
  # pod 'KuiklyNotification', :path => '../KuiklyNotification'

  # Kuikly iOS 渲染库（版本随宿主 Kuikly 版本）
  # pod 'OpenKuiklyIOSRender', '~> 2.24.0'
end
